### ISSUE TITLE
Some white icons for Windows apps are not visible on white background

### ISSUE THREAD

**Issue by bege10** [ueffel/Keypirinha-WindowsApps#7]
Thank you for this package!
With the standard configuration all icons are white.
To see the icons for Windows app and settings on white background I have configured `preferred_contrast = white` . Most icons are black and visible now.
But the icons of Maps, Print 3D, 3D Viewer and Microsoft Store are still white. Can this be changed in Keypirinha-WindowsApps?

**Comment by ueffel** [comment]
It's a problem with the logo caching mechanism.
Keypirinha can only show icons that come from the package itself or from the keypirinha cache directory. So I copy the logos from the path of the windows apps to this cache. This copying is done everytime the catalog refreshes. To stop unnecessary copying the package checks if the logo already exists. This is a problem if you change the `preferred_constrast` setting and file name of the constrast-white- and the constrast-black-logo are the same.

Until I fix this, you can just delete the logo cache `%LOCALAPPDATA%\Keypirinha\Packages\WindowsApps` (installed mode) or `<Keypirinha_Home>\portable\Local\Packages\WindowsApps\` (portable mode)
and execute `Keypirinha: Refresh Catalog: WindowsApps` in keypirinha.

**Comment by bege10** [comment]
Thank you for your answer.
Your suggestion solved the problem for the apps but 3D Viewer. That icon is still white. And now the icon for settings is white.
I deleted the icon cache and changed `preferred_constrast` from white to black and back again and restarted KP several times. But there is no change. App icons remain black, settings icon remains white.

**Comment by ueffel** [comment]
The not-changing settings-icon was my bad in the last commit. Should fine now.

As for the 3D-Viewer: As far as I can see this app does not provide constrast icons. (See `C:\Program Files\WindowsApps\Microsoft.Microsoft3DViewer_7.1908.9012.0_x64__8wekyb3d8bbwe`)

Normally there some constrast logos, for example for the windows weather app there are some in `C:\Program Files\WindowsApps\Microsoft.BingWeather_4.33.13253.0_x64__8wekyb3d8bbwe\Assets\AppTiles\contrast-white`

**Comment by bege10** [comment]
I downloaded v0.8.3, 

deleted the icon cache,
set settings to black,
refreshed the package catalog
= all icons white

repeated the above with settings white
= icons remain white

Which setting is correct for a white background, black or white?

**Comment by ueffel** [comment]
The background of nearly all windows default app logos is transparent. The foreground color changes.
```ini
preferred_contrast = black
```
means the logo has better contrast on dark backgrounds which is why the logo foreground is usally white.
![image](https://user-images.githubusercontent.com/2247384/70260474-a63d8300-1790-11ea-96e6-5eddddfb4aa1.png)

```ini
preferred_contrast = white
```
means the logo has better contrast on light backgrounds which is why the logo foreground is usally black.
![image](https://user-images.githubusercontent.com/2247384/70260847-72af2880-1791-11ea-8191-451264371327.png)


While taking these screenshots I noticed that Keypirinha seems to keep the icons, which were already displayed, cached at runtime and does not seem to refresh if the underlying file changes.
Meaning if I viewed the Weather App icon, then change the `preferred_contrast` and view the Weather App again, the icon does not change. But if I view some other app, like Maps, icon of that is in the `preferred_contrast`.

I'll need to investigate further.

**Comment by ueffel** [comment]
Can you try this and see if it works for you?

[WindowsApps.zip](https://github.com/ueffel/Keypirinha-WindowsApps/files/3929281/WindowsApps.zip)
Rename to `WindowsApps.keypirinha-package`

**Comment by bege10** [comment]
Now both Windows apps and settings icons are correct and are being refreshed as soon as the app setting is changed. Thank you very much for your work.

**Comment by ueffel** [comment]
Alright, I'll make a new version.
